import unittest
from unittest.mock import MagicMock, patch

from equity_auditor import EquityAuditor


class TestEquityAuditor(unittest.TestCase):
    def setUp(self):
        # Mock load_config to avoid actual file read
        with patch("equity_auditor.load_config") as mock_load:
            mock_load.return_value = {
                "ai": {"model_name": "test-model"},
                "strategies": {"test_strategy": {}},
            }
            # Mock commands to avoid initializing real logic
            with (
                patch("equity_auditor.ExtractCommand"),
                patch("equity_auditor.AnalyzeCommand"),
                patch("equity_auditor.IngestCommand"),
                patch("equity_auditor.ResetCommand"),
            ):
                self.auditor = EquityAuditor()

    def test_init(self):
        self.assertIn("extract", self.auditor.commands)
        self.assertIn("analyze", self.auditor.commands)

    @patch("argparse.ArgumentParser.parse_args")
    def test_run_extract(self, mock_args):
        # Configure mock args for 'extract' mode
        mock_args.return_value = MagicMock(
            mode="extract",
            strategy="test_strategy",
            limit=10,
            codes=None,
            output=None,
            debug=False,
            force_refresh=False,
        )

        with patch.object(self.auditor.commands["extract"], "execute") as mock_exec:
            self.auditor.run()
            mock_exec.assert_called_once_with(
                strategy="test_strategy", limit=10, codes=None, output_path=None
            )

    @patch("argparse.ArgumentParser.parse_args")
    def test_run_analyze(self, mock_args):
        # Configure mock args for 'analyze' mode
        mock_args.return_value = MagicMock(
            mode="analyze",
            strategy="test_strategy",
            limit=5,
            codes="1001,1002",
            files=None,
            debug=True,
            force_refresh=True,
        )

        with patch.object(self.auditor.commands["analyze"], "execute") as mock_exec:
            self.auditor.run()
            # Check if debug mode propagated
            self.assertTrue(self.auditor.commands["analyze"].debug_mode)
            # Check execute call
            mock_exec.assert_called_once_with(
                strategy="test_strategy",
                limit=5,
                codes=["1001", "1002"],
                files=None,
                force_refresh=True,
            )
            # Check auto-report generation -> ReportGenerator is not used in EquityAuditor directly.
            # Reports are generated by AnalyzeCommand logic.

    @patch("argparse.ArgumentParser.parse_args")
    def test_run_reset(self, mock_args):
        mock_args.return_value = MagicMock(
            mode="reset",
            strategy="test_strategy",
            codes="3498",
            all=False,
            force=True,  # reset uses force as fallback for all? Parser logic: reset_all=args.all if ... else args.force
            debug=False,
        )

        with patch.object(self.auditor.commands["reset"], "execute") as mock_exec:
            self.auditor.run()
            mock_exec.assert_called_once()
            args, kwargs = mock_exec.call_args
            self.assertEqual(kwargs["strategy"], "test_strategy")
            self.assertEqual(kwargs["code"], "3498")


if __name__ == "__main__":
    unittest.main()
